FROM golang:alpine

MAINTAINER EWETUMO ALEXANDER 	<trinoxf@gmail.com>

RUN apt-get update -y
RUN apt-get install -y software-properties-common
RUN apt-add-repository -y "ppa:ubuntu-lxc/stable"
RUN apt-get update -y
RUN apt-get install -y lxc libpcap-dev lxc-templates lxc-dev git

